/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Start = {
  icon?: string;
  value?: string;
};

export type End = {
  icon?: string;
  value?: string;
};

export type FieldRange = {
  _type: "fieldRange";
  from?: number;
  to?: number;
};

export type FieldItem = {
  _type: "fieldItem";
  id?: string;
  title?: string;
  description?: string;
  range?: FieldRange;
};

export type FieldInterest = {
  _type: "fieldInterest";
  id?: string;
  label?: string;
  description?: string;
};

export type FieldOption = {
  _type: "fieldOption";
  id?: string;
  label?: string;
  description?: string;
  interests?: Array<
    {
      _key: string;
    } & FieldInterest
  >;
};

export type FieldIcons = {
  _type: "fieldIcons";
  start?: Start;
  end?: End;
};

export type FieldDescription = {
  _type: "fieldDescription";
  value?: string;
  path?: string;
  newTab?: boolean;
};

export type FormField = {
  _type: "formField";
  name?: string;
  type?:
    | "text"
    | "email"
    | "tel"
    | "number"
    | "date"
    | "datetime-local"
    | "textarea"
    | "select"
    | "checkbox"
    | "radio"
    | "file"
    | "size";
  label?: string;
  placeholder?: string;
  description?: FieldDescription;
  required?: boolean;
  errMsg?: string;
  group?: string;
  defaultValue?: string;
  min?: number;
  max?: number;
  size?: number;
  icons?: FieldIcons;
  options?: Array<
    {
      _key: string;
    } & FieldOption
  >;
  items?: Array<
    {
      _key: string;
    } & FieldItem
  >;
  sizes?: Array<string>;
};

export type FormCard = {
  _type: "formCard";
  title?: string;
  info?: string;
  description?: string;
  fields?: Array<
    {
      _key: string;
    } & FormField
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Inquiry = {
  _id: string;
  _type: "inquiry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  email?: string;
  phone?: string;
  eventType?: "wedding" | "prom" | "reception" | "special-occasion";
  eventDate?: string;
  budget?: string;
  dreamDress?: string;
  inspirationPhotos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  status?: "new" | "contacted" | "in-progress" | "completed" | "archived";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  items?: Array<{
    product?: ProductReference;
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  total?: number;
  status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
  clerkUserId?: string;
  email?: string;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  paymentMethod?: "stripe" | "paypal";
  paymentStatus?: "pending" | "paid" | "refunded" | "failed";
  stripePaymentId?: string;
  stripeSessionId?: string;
  paypalOrderId?: string;
  paidAt?: string;
  createdAt?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type ProductColorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productColor";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  description?: string;
  delivery?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category?: CategoryReference;
  sizes?: Array<string>;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  stock?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ProductColor = {
  _id: string;
  _type: "productColor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  value?: Color;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type ConsultationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "consultation";
};

export type Booking = {
  _id: string;
  _type: "booking";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consultation?: ConsultationReference;
  dateTime?: string;
  customerName?: string;
  customerEmail?: string;
  customerPhone?: string;
  status?: "pending" | "paid" | "confirmed" | "delivered" | "cancelled";
  paymentMethod?: "stripe" | "paypal";
  stripeSessionId?: string;
  paypalOrderId?: string;
  formFields?: Array<{
    fieldName?: string;
    fieldLabel?: string;
    fieldType?: string;
    value?: string;
    _type: "formFieldAnswer";
    _key: string;
  }>;
};

export type BlockedSlot = {
  _id: string;
  _type: "blockedSlot";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consultation?: ConsultationReference;
  date?: string;
  allDay?: boolean;
  startTime?: string;
  duration?: number;
  message?: string;
};

export type Consultation = {
  _id: string;
  _type: "consultation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  duration?: number;
  price?: number;
  dresses?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  includes?: Array<string>;
  formCards?: Array<
    {
      _key: string;
    } & FormCard
  >;
  order?: number;
  onPMPage?: boolean;
};

export type BusinessHours = {
  _id: string;
  _type: "businessHours";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hours?: Array<{
    day?:
      | "Monday"
      | "Tuesday"
      | "Wednesday"
      | "Thursday"
      | "Friday"
      | "Saturday"
      | "Sunday";
    isOpen?: boolean;
    startTime?: string;
    endTime?: string;
    _key: string;
  }>;
};

export type PricingTier = {
  _id: string;
  _type: "pricingTier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  price?: number;
  description?: string;
  features?: Array<string>;
  order?: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
};

export type Social = {
  _id: string;
  _type: "social";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  url?: string;
  icon?: string;
};

export type Permissions = {
  _id: string;
  _type: "permissions";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  customerName?: string;
  customerEmail?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: "pending" | "approved" | "denied";
  name?: string;
  service?: string;
  review?: string;
  rating?: number;
  date?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  workAssets?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "asset";
    _key: string;
  }>;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type CancellationPolicy = {
  _id: string;
  _type: "cancellationPolicy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icon?: string;
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: CategoryReference;
  featured?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Start
  | End
  | FieldRange
  | FieldItem
  | FieldInterest
  | FieldOption
  | FieldIcons
  | FieldDescription
  | FormField
  | FormCard
  | SanityImageAssetReference
  | Inquiry
  | SanityImageCrop
  | SanityImageHotspot
  | ProductReference
  | Order
  | CategoryReference
  | ProductColorReference
  | Product
  | Slug
  | ProductColor
  | Color
  | ConsultationReference
  | Booking
  | BlockedSlot
  | Consultation
  | BusinessHours
  | PricingTier
  | Faq
  | Social
  | Permissions
  | Testimonial
  | Hero
  | CancellationPolicy
  | Gallery
  | Category
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/blockedSlot.ts
// Variable: BLOCKED_SLOTS_QUERY
// Query: *[_type == "blockedSlot" && date == $date && ( !defined($consultationId) || consultation._ref == $consultationId || consultation._ref == null) ] {    allDay,    startTime,    duration,    message,    "consultationDuration": consultation->duration  }
export type BLOCKED_SLOTS_QUERY_RESULT = Array<{
  allDay: boolean | null;
  startTime: string | null;
  duration: number | null;
  message: string | null;
  consultationDuration: number | null;
}>;

// Source: sanity/queries/blockedSlot.ts
// Variable: BOOKINGS_FOR_DATE_QUERY
// Query: *[_type == "booking" && consultation._ref == $consultationId && dateTime >= $start && dateTime < $end] {    dateTime  }
export type BOOKINGS_FOR_DATE_QUERY_RESULT = Array<{
  dateTime: string | null;
}>;

// Source: sanity/queries/cancellationPolicy.ts
// Variable: CANCELLATION_POLICY_QUERY
// Query: *[_type == "cancellationPolicy"]{        _id,        title,        description,        icon,    }
export type CANCELLATION_POLICY_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  icon: string | null;
}>;

// Source: sanity/queries/category.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(_createdAt desc) {        _id,        name,        "slug": slug.current    }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
}>;

// Source: sanity/queries/color.ts
// Variable: PRODUCT_COLOR_QUERY
// Query: *[_type == "productColor"]{  name,  "hex": value.hex}
export type PRODUCT_COLOR_QUERY_RESULT = Array<{
  name: string | null;
  hex: string | null;
}>;

// Source: sanity/queries/consultation.ts
// Variable: CONSULTATION_QUERY
// Query: *[  _type == "consultation" &&  ($onPMPage == null || onPMPage == $onPMPage)] | order(order asc, _createdAt asc) {  _id,  title,  "slug": slug.current,  description,  duration,  price,  dresses,  order,  onPMPage,  "image": image.asset->url,  includes[],  formCards[] {    title,    info,    description,    fields[] {      name,      type,      label,      placeholder,      description {        value,        path,        newTab      },      required,      errMsg,      group,      defaultValue,      min,      max,      size,      icons {        start {          icon,          value        },        end {          icon,          value        }      },      sizes[],      options[] {        id,        label,        description,        interests[] {          id,          label,          description        }      },      items[] {        id,        title,        description,        range {          from,          to        }      }    }  }}
export type CONSULTATION_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  duration: number | null;
  price: number | null;
  dresses: number | null;
  order: number | null;
  onPMPage: boolean | null;
  image: string | null;
  includes: Array<string> | null;
  formCards: Array<{
    title: string | null;
    info: string | null;
    description: string | null;
    fields: Array<{
      name: string | null;
      type:
        | "checkbox"
        | "date"
        | "datetime-local"
        | "email"
        | "file"
        | "number"
        | "radio"
        | "select"
        | "size"
        | "tel"
        | "text"
        | "textarea"
        | null;
      label: string | null;
      placeholder: string | null;
      description: {
        value: string | null;
        path: string | null;
        newTab: boolean | null;
      } | null;
      required: boolean | null;
      errMsg: string | null;
      group: string | null;
      defaultValue: string | null;
      min: number | null;
      max: number | null;
      size: number | null;
      icons: {
        start: {
          icon: string | null;
          value: string | null;
        } | null;
        end: {
          icon: string | null;
          value: string | null;
        } | null;
      } | null;
      sizes: Array<string> | null;
      options: Array<{
        id: string | null;
        label: string | null;
        description: string | null;
        interests: Array<{
          id: string | null;
          label: string | null;
          description: string | null;
        }> | null;
      }> | null;
      items: Array<{
        id: string | null;
        title: string | null;
        description: string | null;
        range: {
          from: number | null;
          to: number | null;
        } | null;
      }> | null;
    }> | null;
  }> | null;
}>;

// Source: sanity/queries/consultation.ts
// Variable: CONSULTATION_BY_SLUG_QUERY
// Query: *[  _type == "consultation" &&  slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  description,  duration,  price,  dresses,  order,  onPMPage,  "image": image.asset->url,  includes[],  formCards[] {    title,    info,    description,    fields[] {      name,      type,      label,      placeholder,      description {        value,        path,        newTab      },      required,      errMsg,      group,      defaultValue,      min,      max,      size,      icons {        start {          icon,          value        },        end {          icon,          value        }      },      sizes[],      options[] {        id,        label,        description,        interests[] {          id,          label,          description        }      },      items[] {        id,        title,        description,        range {          from,          to        }      }    }  }}
export type CONSULTATION_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  duration: number | null;
  price: number | null;
  dresses: number | null;
  order: number | null;
  onPMPage: boolean | null;
  image: string | null;
  includes: Array<string> | null;
  formCards: Array<{
    title: string | null;
    info: string | null;
    description: string | null;
    fields: Array<{
      name: string | null;
      type:
        | "checkbox"
        | "date"
        | "datetime-local"
        | "email"
        | "file"
        | "number"
        | "radio"
        | "select"
        | "size"
        | "tel"
        | "text"
        | "textarea"
        | null;
      label: string | null;
      placeholder: string | null;
      description: {
        value: string | null;
        path: string | null;
        newTab: boolean | null;
      } | null;
      required: boolean | null;
      errMsg: string | null;
      group: string | null;
      defaultValue: string | null;
      min: number | null;
      max: number | null;
      size: number | null;
      icons: {
        start: {
          icon: string | null;
          value: string | null;
        } | null;
        end: {
          icon: string | null;
          value: string | null;
        } | null;
      } | null;
      sizes: Array<string> | null;
      options: Array<{
        id: string | null;
        label: string | null;
        description: string | null;
        interests: Array<{
          id: string | null;
          label: string | null;
          description: string | null;
        }> | null;
      }> | null;
      items: Array<{
        id: string | null;
        title: string | null;
        description: string | null;
        range: {
          from: number | null;
          to: number | null;
        } | null;
      }> | null;
    }> | null;
  }> | null;
} | null;

// Source: sanity/queries/faq.ts
// Variable: FAQ_QUERY
// Query: *[_type == "faq"] | order(_createdAt asc) {_id,  question,  answer}
export type FAQ_QUERY_RESULT = Array<{
  _id: string;
  question: string | null;
  answer: string | null;
}>;

// Source: sanity/queries/gallery.ts
// Variable: GALLERY_QUERY
// Query: *[_type == "gallery"] | order(_createdAt asc){  _id,  "image": image.asset->url,  "width": image.asset->metadata.dimensions.width,  "height": image.asset->metadata.dimensions.height,  category->{    name,    "slug": slug.current  }}
export type GALLERY_QUERY_RESULT = Array<{
  _id: string;
  image: string | null;
  width: number | null;
  height: number | null;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/queries/gallery.ts
// Variable: FEATURED_GALLERY_QUERY
// Query: *[_type == "gallery" && featured == true  && (!defined($category) || category->slug.current == $category)]| order(_createdAt asc)[$start...$end]{  _id,  "image": image.asset->url,  "width": image.asset->metadata.dimensions.width,  "height": image.asset->metadata.dimensions.height,  category->{    name,    "slug": slug.current  }}
export type FEATURED_GALLERY_QUERY_RESULT = Array<{
  _id: string;
  image: string | null;
  width: number | null;
  height: number | null;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/queries/hero.ts
// Variable: HERO_QUERY
// Query: *[_type == "hero"] | order(_createdAt desc) {        _id,        "image": image.asset->url,        alt    }
export type HERO_QUERY_RESULT = Array<{
  _id: string;
  image: string | null;
  alt: string | null;
}>;

// Source: sanity/queries/hours.ts
// Variable: BUSINESS_HOUR_QUERY
// Query: *[_type == "businessHours"]{  hours[]}[0]
export type BUSINESS_HOUR_QUERY_RESULT = {
  hours: Array<{
    day?:
      | "Friday"
      | "Monday"
      | "Saturday"
      | "Sunday"
      | "Thursday"
      | "Tuesday"
      | "Wednesday";
    isOpen?: boolean;
    startTime?: string;
    endTime?: string;
    _key: string;
  }> | null;
} | null;

// Source: sanity/queries/orders.ts
// Variable: ORDERS_BY_USER_QUERY
// Query: *[  _type == "order"  && clerkUserId == $clerkUserId] | order(createdAt desc) {  _id,  orderNumber,  total,  status,  createdAt,  "itemCount": count(items),  "itemNames": items[].product->name,  "itemImages": items[].product->images[0].asset->url}
export type ORDERS_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "pending" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  itemNames: Array<string | null> | null;
  itemImages: Array<string | null> | null;
}>;

// Source: sanity/queries/orders.ts
// Variable: ORDER_BY_ID_QUERY
// Query: *[  _type == "order"  && _id == $id][0] {  _id,  orderNumber,  clerkUserId,  email,  items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      name,      "slug": slug.current,      "image": images[0].asset->url    }  },  total,  status,  address{    name,    line1,    line2,    city,    postcode,    country  },  stripePaymentId,  createdAt}
export type ORDER_BY_ID_QUERY_RESULT = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  email: string | null;
  items: Array<{
    _key: string;
    quantity: number | null;
    priceAtPurchase: number | null;
    product: {
      _id: string;
      name: string | null;
      slug: string | null;
      image: string | null;
    } | null;
  }> | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "pending" | "shipped" | null;
  address: {
    name: string | null;
    line1: string | null;
    line2: string | null;
    city: string | null;
    postcode: string | null;
    country: string | null;
  } | null;
  stripePaymentId: string | null;
  createdAt: string | null;
} | null;

// Source: sanity/queries/orders.ts
// Variable: RECENT_ORDERS_QUERY
// Query: *[  _type == "order"] | order(createdAt desc) [0...$limit] {  _id,  orderNumber,  email,  total,  status,  createdAt}
export type RECENT_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  email: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "pending" | "shipped" | null;
  createdAt: string | null;
}>;

// Source: sanity/queries/orders.ts
// Variable: ORDER_BY_STRIPE_PAYMENT_ID_QUERY
// Query: *[  _type == "order"  && stripePaymentId == $stripePaymentId][0]{ _id }
export type ORDER_BY_STRIPE_PAYMENT_ID_QUERY_RESULT = {
  _id: string;
} | null;

// Source: sanity/queries/orders.ts
// Variable: ORDER_BY_STRIPE_SESSION_ID_QUERY
// Query: *[  _type == "order"  && stripeSessionId == $sessionId][0]{ _id }
export type ORDER_BY_STRIPE_SESSION_ID_QUERY_RESULT = {
  _id: string;
} | null;

// Source: sanity/queries/permission.ts
// Variable: REVIEW_PERMISSION_QUERY
// Query: *[_type == "permissions" && lower(customerEmail) == lower($email)][0]
export type REVIEW_PERMISSION_QUERY_RESULT = {
  _id: string;
  _type: "permissions";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  customerName?: string;
  customerEmail?: string;
} | null;

// Source: sanity/queries/pricing.ts
// Variable: PRICING_TIERS_QUERY
// Query: *[_type == "pricingTier"] | order(order asc, _createdAt asc) {  _id,  name,  price,  description,  features}
export type PRICING_TIERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  price: number | null;
  description: string | null;
  features: Array<string> | null;
}>;

// Source: sanity/queries/product.ts
// Variable: PRODUCT_QUERY
// Query: *[_type == "product"] | order(_createdAt desc) {    _id,    name,    "slug": slug.current,    price,    colors[]->{name, "value": value.hex},    description,    delivery,    "images": images[].asset->url,    sizes,    stock,    delivery,    category -> {        _id,        name,        "slug": slug.current    },}
export type PRODUCT_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  colors: Array<{
    name: string | null;
    value: string | null;
  }> | null;
  description: string | null;
  delivery: string | null;
  images: Array<string | null> | null;
  sizes: Array<string> | null;
  stock: number | null;
  category: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/queries/product.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(_createdAt desc)[0] {    _id,    name,    "slug": slug.current,    price,    colors[]->{name, "value": value.hex},    description,    "images": images[].asset->url,    sizes,    stock,    delivery,    category -> {        _id,        name,        "slug": slug.current    },}
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  colors: Array<{
    name: string | null;
    value: string | null;
  }> | null;
  description: string | null;
  images: Array<string | null> | null;
  sizes: Array<string> | null;
  stock: number | null;
  delivery: string | null;
  category: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
} | null;

// Source: sanity/queries/product.ts
// Variable: PRODUCT_BY_IDS_QUERY
// Query: *[_type == "product" && _id in $ids] | order(_createdAt desc) {    _id,    name,    "slug": slug.current,    price,    colors[]->{name, "value": value.hex},    description,    "images": images[].asset->url,    sizes,    stock,    delivery,    category -> {        _id,        name,        "slug": slug.current    },}
export type PRODUCT_BY_IDS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  colors: Array<{
    name: string | null;
    value: string | null;
  }> | null;
  description: string | null;
  images: Array<string | null> | null;
  sizes: Array<string> | null;
  stock: number | null;
  delivery: string | null;
  category: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/queries/review.ts
// Variable: REVIEW_QUERY
// Query: *[_type == "testimonial" && status == "approved"] | order(date desc) {    _id,    "avatar": avatar.asset->url,    service,    date,    name,    rating,    review,    "workAssets": workAssets[].asset->url}
export type REVIEW_QUERY_RESULT = Array<{
  _id: string;
  avatar: string | null;
  service: string | null;
  date: string | null;
  name: string | null;
  rating: number | null;
  review: string | null;
  workAssets: Array<string | null> | null;
}>;

// Source: sanity/queries/socials.ts
// Variable: SOCIAL_QUERY
// Query: *[_type == "social"] | order(_createdAt desc) {        _id,        name,        url,        icon    }
export type SOCIAL_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  url: string | null;
  icon: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "blockedSlot" && date == $date && ( !defined($consultationId) || consultation._ref == $consultationId || consultation._ref == null) ] {\n    allDay,\n    startTime,\n    duration,\n    message,\n    "consultationDuration": consultation->duration\n  }\n': BLOCKED_SLOTS_QUERY_RESULT;
    '\n  *[_type == "booking" && consultation._ref == $consultationId && dateTime >= $start && dateTime < $end] {\n    dateTime\n  }\n': BOOKINGS_FOR_DATE_QUERY_RESULT;
    '\n    *[_type == "cancellationPolicy"]{\n        _id,\n        title,\n        description,\n        icon,\n    }\n': CANCELLATION_POLICY_QUERY_RESULT;
    '\n    *[_type == "category"] | order(_createdAt desc) {\n        _id,\n        name,\n        "slug": slug.current\n    }\n': CATEGORIES_QUERY_RESULT;
    '\n*[_type == "productColor"]{\n  name,\n  "hex": value.hex\n}\n': PRODUCT_COLOR_QUERY_RESULT;
    '\n*[\n  _type == "consultation" &&\n  ($onPMPage == null || onPMPage == $onPMPage)\n] | order(order asc, _createdAt asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  duration,\n  price,\n  dresses,\n  order,\n  onPMPage,\n\n  "image": image.asset->url,\n\n  includes[],\n\n  formCards[] {\n    title,\n    info,\n    description,\n\n    fields[] {\n      name,\n      type,\n      label,\n      placeholder,\n\n      description {\n        value,\n        path,\n        newTab\n      },\n\n      required,\n      errMsg,\n      group,\n      defaultValue,\n      min,\n      max,\n      size,\n\n      icons {\n        start {\n          icon,\n          value\n        },\n        end {\n          icon,\n          value\n        }\n      },\n\n      sizes[],\n\n      options[] {\n        id,\n        label,\n        description,\n\n        interests[] {\n          id,\n          label,\n          description\n        }\n      },\n\n      items[] {\n        id,\n        title,\n        description,\n\n        range {\n          from,\n          to\n        }\n      }\n    }\n  }\n}\n': CONSULTATION_QUERY_RESULT;
    '\n*[\n  _type == "consultation" &&\n  slug.current == $slug\n][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  duration,\n  price,\n  dresses,\n  order,\n  onPMPage,\n\n  "image": image.asset->url,\n\n  includes[],\n\n  formCards[] {\n    title,\n    info,\n    description,\n\n    fields[] {\n      name,\n      type,\n      label,\n      placeholder,\n\n      description {\n        value,\n        path,\n        newTab\n      },\n\n      required,\n      errMsg,\n      group,\n      defaultValue,\n      min,\n      max,\n      size,\n\n      icons {\n        start {\n          icon,\n          value\n        },\n        end {\n          icon,\n          value\n        }\n      },\n\n      sizes[],\n\n      options[] {\n        id,\n        label,\n        description,\n\n        interests[] {\n          id,\n          label,\n          description\n        }\n      },\n\n      items[] {\n        id,\n        title,\n        description,\n\n        range {\n          from,\n          to\n        }\n      }\n    }\n  }\n}\n': CONSULTATION_BY_SLUG_QUERY_RESULT;
    '\n*[_type == "faq"] | order(_createdAt asc) {\n_id,\n  question,\n  answer\n}\n': FAQ_QUERY_RESULT;
    '\n*[_type == "gallery"] | order(_createdAt asc){\n  _id,\n  "image": image.asset->url,\n  "width": image.asset->metadata.dimensions.width,\n  "height": image.asset->metadata.dimensions.height,\n  category->{\n    name,\n    "slug": slug.current\n  }\n}\n': GALLERY_QUERY_RESULT;
    '\n*[_type == "gallery"\n && featured == true\n  && (!defined($category) || category->slug.current == $category)\n]\n| order(_createdAt asc)\n[$start...$end]{\n  _id,\n  "image": image.asset->url,\n  "width": image.asset->metadata.dimensions.width,\n  "height": image.asset->metadata.dimensions.height,\n  category->{\n    name,\n    "slug": slug.current\n  }\n}\n': FEATURED_GALLERY_QUERY_RESULT;
    '\n    *[_type == "hero"] | order(_createdAt desc) {\n        _id,\n        "image": image.asset->url,\n        alt\n    }\n': HERO_QUERY_RESULT;
    '\n    *[_type == "businessHours"]{\n  hours[]\n}[0]\n': BUSINESS_HOUR_QUERY_RESULT;
    '*[\n  _type == "order"\n  && clerkUserId == $clerkUserId\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  total,\n  status,\n  createdAt,\n  "itemCount": count(items),\n  "itemNames": items[].product->name,\n  "itemImages": items[].product->images[0].asset->url\n}': ORDERS_BY_USER_QUERY_RESULT;
    '*[\n  _type == "order"\n  && _id == $id\n][0] {\n  _id,\n  orderNumber,\n  clerkUserId,\n  email,\n  items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      name,\n      "slug": slug.current,\n      "image": images[0].asset->url\n    }\n  },\n  total,\n  status,\n  address{\n    name,\n    line1,\n    line2,\n    city,\n    postcode,\n    country\n  },\n  stripePaymentId,\n  createdAt\n}': ORDER_BY_ID_QUERY_RESULT;
    '*[\n  _type == "order"\n] | order(createdAt desc) [0...$limit] {\n  _id,\n  orderNumber,\n  email,\n  total,\n  status,\n  createdAt\n}': RECENT_ORDERS_QUERY_RESULT;
    '*[\n  _type == "order"\n  && stripePaymentId == $stripePaymentId\n][0]{ _id }': ORDER_BY_STRIPE_PAYMENT_ID_QUERY_RESULT;
    '*[\n  _type == "order"\n  && stripeSessionId == $sessionId\n][0]{ _id }': ORDER_BY_STRIPE_SESSION_ID_QUERY_RESULT;
    '*[_type == "permissions" && lower(customerEmail) == lower($email)][0]': REVIEW_PERMISSION_QUERY_RESULT;
    '\n*[_type == "pricingTier"] | order(order asc, _createdAt asc) {\n  _id,\n  name,\n  price,\n  description,\n  features\n}\n': PRICING_TIERS_QUERY_RESULT;
    '\n*[_type == "product"] | order(_createdAt desc) {\n    _id,\n    name,\n    "slug": slug.current,\n    price,\n    colors[]->{name, "value": value.hex},\n    description,\n    delivery,\n    "images": images[].asset->url,\n    sizes,\n    stock,\n    delivery,\n    category -> {\n        _id,\n        name,\n        "slug": slug.current\n    },\n}\n': PRODUCT_QUERY_RESULT;
    '\n*[_type == "product" && slug.current == $slug] | order(_createdAt desc)[0] {\n    _id,\n    name,\n    "slug": slug.current,\n    price,\n    colors[]->{name, "value": value.hex},\n    description,\n    "images": images[].asset->url,\n    sizes,\n    stock,\n    delivery,\n    category -> {\n        _id,\n        name,\n        "slug": slug.current\n    },\n}\n': PRODUCT_BY_SLUG_QUERY_RESULT;
    '\n*[_type == "product" && _id in $ids] | order(_createdAt desc) {\n    _id,\n    name,\n    "slug": slug.current,\n    price,\n    colors[]->{name, "value": value.hex},\n    description,\n    "images": images[].asset->url,\n    sizes,\n    stock,\n    delivery,\n    category -> {\n        _id,\n        name,\n        "slug": slug.current\n    },\n}\n': PRODUCT_BY_IDS_QUERY_RESULT;
    '\n*[_type == "testimonial" && status == "approved"] | order(date desc) {\n    _id,\n    "avatar": avatar.asset->url,\n    service,\n    date,\n    name,\n    rating,\n    review,\n    "workAssets": workAssets[].asset->url\n}\n': REVIEW_QUERY_RESULT;
    '\n    *[_type == "social"] | order(_createdAt desc) {\n        _id,\n        name,\n        url,\n        icon\n    }\n': SOCIAL_QUERY_RESULT;
  }
}
